project:
  useAWS: False 
  awsSetup:
    bucket: projects.irll # working bucket in AWS
    region: ca-central-1 # working AWS region
    rootDomain: irll.net # a fully qualified domain name without 'https://'
    cpu: 2 # int 1,2, or 4
    memory: 10 # int 1-30

  events:
    startServerStep: 1 # int ? #this
    stopServerStep: 9
  id: exp-lunar-lander-binary-feedback # Letters, Numbers and '-' only! #only lower case #change this
  live: True # bool
  maxRuntime: 90 # int in minutes.
  name: lunar_lander_binary_feedback # str #change this 
  researcher: Edan Meyer
  ssl:
    fullchain: SSL/fullchain.pem # path to fullchain.pem file excluding bucket name
    privkey: SSL/privkey.pem # path to privkey.pem file excluding bucket name
    sslBucket: projects.irll # bucket name for resolving paths above

  steps: #in the step file folder # any number of steps needed with corresponding filenames
    1: consentForm.html
    2: initialLunarLanderSurvey.html
    3: lunarLanderPlayInstructions.html
    4: game
    5: feedbackInstructions.html
    6: game
    7: postGameSurvey.html
    8: uuidScreen.html
    9: endScreen.html
    finalStep: endScreen.html #put the file name of the last step again here # required, filename can be same as last numbered step
  teamMembers: Edan # str

trial:
  trial_types:
    - play_game
    - give_feedback
  actionBufferLifespan: 1 # int
  maxEpisodes: 3 # int
  game: LunarLanderContinuous-v2 # full environment name
  dataFile: trial # episode or trial
  s3upload: True
  validKeys: ['ArrowLeft', 'ArrowRight', 'ArrowUp']
  continuousActionSpace: # the appropriate action space for environment.
    - [null, [0, 0]]
    - [[], [0, 0]]
    - [['ArrowLeft'], [0, -1]]
    - [['ArrowRight'], [0, 1]]
    - [['ArrowLeft', 'ArrowRight'], [0, 0]]
    - [['ArrowUp'], [1, 0]]
    - [['ArrowLeft', 'ArrowUp'], [1, -1]]
    - [['ArrowRight', 'ArrowUp'], [1, 1]]
    - [['ArrowLeft', 'ArrowRight', 'ArrowUp'], [1, 0]]
  frameRateStepSize: 5 # int Optional if allowFrameRateChange = False
  minFrameRate: 1 # int Optional if allowFrameRateChange = False
  maxFrameRate: 60 # int Optional if allowFrameRateChange = False
  frameskip: 1 # int Optional how many frames to skip for playing game phase
  allowFrameRateChange: False # bool
  startingFrameRate: 20 # int Required
  play_game_ui: # to include ui button set to True, False buttons will not be shown
    left: True
    right: True
    up: True
    down: False
    start: True
    stop: True # TODO: Change back to false
    pause: True
    reset: False
    trainOffline: False
    trainOnline: False
    good: False
    bad: False
    fpsSet: False
    fpsUp: False
    fpsDown: False
  give_feedback_ui: # to include ui button set to True, False buttons will not be shown
    left: False
    right: False
    up: False
    down: False
    start: True
    stop: True # TODO: Change back to false
    pause: True
    reset: False
    trainOffline: False
    trainOnline: False
    good: True
    bad: True
    fpsSet: False
    fpsUp: False
    fpsDown: False