trial:
  actionBufferLifespan: 1
  allowFrameRateChange: false
  bucket: projects.irll
  continuousActionSpace:
  - - null
    - - 0
      - 0
  - - []
    - - 0
      - 0
  - - - ArrowLeft
    - - 0
      - -1
  - - - ArrowRight
    - - 0
      - 1
  - - - ArrowLeft
      - ArrowRight
    - - 0
      - 0
  - - - ArrowUp
    - - 1
      - 0
  - - - ArrowLeft
      - ArrowUp
    - - 1
      - -1
  - - - ArrowRight
      - ArrowUp
    - - 1
      - 1
  - - - ArrowLeft
      - ArrowRight
      - ArrowUp
    - - 1
      - 0
  dataFile: trial
  frameRateStepSize: 5
  frameskip: 1
  game: LunarLanderContinuous-v2
  give_feedback_ui:
  - start
  - stop
  - pause
  - good
  - bad
  maxEpisodes: 3
  maxFrameRate: 60
  minFrameRate: 1
  play_game_ui:
  - left
  - right
  - up
  - start
  - stop
  - pause
  projectId: exp-lunar-lander-binary-feedback
  s3upload: true
  startingFrameRate: 20
  trial_types:
  - play_game
  - play_game
  - play_game
  - give_feedback
  - give_feedback
  - give_feedback
  validKeys:
  - ArrowLeft
  - ArrowRight
  - ArrowUp
