trial:
  actionBufferLifespan: 1
  actionSpace:
  - noop
  - fire
  - up
  - down
  - rightfire
  - leftfire
  allowFrameRateChange: false
  bucket: projects.irll
  dataFile: episode
  frameRateStepSize: 5
  frameskip: 1
  game: ALE/Pong-v5
  give_feedback_ui:
  - start
  - stop
  - pause
  - good
  - bad
  maxEpisodeFrames: 300
  maxEpisodes: 1
  maxFrameRate: 60
  minFrameRate: 1
  play_game_ui:
  - up
  - down
  - start
  - stop
  - pause
  projectId: exp-pong-binary-feedback
  s3upload: true
  startingFrameRate: 60
  trial_types:
  - play_game
  - play_game
  - play_game
  - give_feedback
  - give_feedback
  - give_feedback
